### ISSUE TITLE
Can't change title of education

### ISSUE THREAD

**Issue by luttje** [StudioKaa/current#44]
Rather annoying because we can't change an incorrect name at the moment without losing all contents of the education.

I'm assuming this is disabled because of the name being turned into a slug for URL's. That's dumb, don't do that please.

If you want someone to help in fixing this I'd be glad to call in @Feddman

**Comment by bartjroos** [comment]
It's because of the folder-structure on DigitalOcean Spaces. It needs to be like this for syncing to mijnportaal, which is mandatory because CurrApp is not an ROC-standard. When creating an education, it is stated that you can't change the title later on. Sorry...
